#!/usr/bin/env node
// CI tool: populate npm/vendor/<os-arch>/ with verified binaries from
// the GitHub Release artifacts produced by .github/workflows/release.yml.
//
// Inputs (flags):
//   --version X.Y.Z         release version without the leading `v`
//   --dist <path>           directory containing the downloaded artifacts
//                           (tar.gz + .sha256 for posix, .zip + .sha256
//                            for windows, plus SHA256SUMS aggregate)
//   --npm <path>            path to the npm package root (default: the
//                           parent directory of this script)
//
// Behavior:
//   1. For every supported (npm os-arch, zig triple) tuple, locate the
//      release artifact in --dist.
//   2. Verify the per-artifact .sha256 sidecar matches the line in
//      SHA256SUMS (defense in depth — both must agree).
//   3. Re-hash the artifact ourselves and confirm it matches the
//      sidecar value, so a tampered sidecar cannot bless a tampered
//      artifact.
//   4. Extract the binary; copy it to <npm>/vendor/<os-arch>/.
//   5. chmod +x the posix binaries.
//   6. Rewrite <npm>/package.json with the release version.
//   7. Print a summary table so the CI log makes the contents auditable.
//
// Fail-fast on any verification mismatch or missing artifact. There is
// no point publishing a tarball that ships unverified or partial
// binaries.

import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import {
  copyFileSync,
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";

const PLATFORMS = [
  { npmKey: "darwin-x64", triple: "x86_64-macos", ext: "tar.gz", exe: "cr" },
  { npmKey: "darwin-arm64", triple: "aarch64-macos", ext: "tar.gz", exe: "cr" },
  { npmKey: "linux-x64", triple: "x86_64-linux", ext: "tar.gz", exe: "cr" },
  { npmKey: "linux-arm64", triple: "aarch64-linux", ext: "tar.gz", exe: "cr" },
  // Windows artifacts land as `cr-<version>-<arch>-windows-preview.zip`.
  // The `-preview` tag is intentional and matches release.yml; it is not
  // a release-channel marker, it is the platform-tier marker.
  { npmKey: "win32-x64", triple: "x86_64-windows-preview", ext: "zip", exe: "cr.exe" },
  { npmKey: "win32-arm64", triple: "aarch64-windows-preview", ext: "zip", exe: "cr.exe" },
];

function parseArgs(argv) {
  const out = { version: null, dist: null, npm: null };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === "--version") out.version = argv[++i];
    else if (a === "--dist") out.dist = argv[++i];
    else if (a === "--npm") out.npm = argv[++i];
    else if (a === "--help" || a === "-h") {
      process.stdout.write(
        "Usage: prepare.mjs --version X.Y.Z --dist <path> [--npm <path>]\n",
      );
      process.exit(0);
    } else {
      throw new Error(`unknown arg: ${a}`);
    }
  }
  if (!out.version) throw new Error("missing --version");
  if (!out.dist) throw new Error("missing --dist");
  return out;
}

function sha256File(path) {
  const buf = readFileSync(path);
  return createHash("sha256").update(buf).digest("hex");
}

function loadSha256Sums(path) {
  // SHA256SUMS lines look like: "<hex>  <filename>\n"
  const text = readFileSync(path, "utf8");
  const map = new Map();
  for (const line of text.split(/\r?\n/)) {
    if (!line.trim()) continue;
    const [hex, ...rest] = line.split(/\s+/);
    if (!hex || rest.length === 0) continue;
    map.set(rest.join(" "), hex.toLowerCase());
  }
  return map;
}

function extractArchive(archivePath, ext, destDir) {
  mkdirSync(destDir, { recursive: true });
  let cmd;
  let args;
  if (ext === "tar.gz") {
    cmd = "tar";
    args = ["-xzf", archivePath, "-C", destDir];
  } else if (ext === "zip") {
    cmd = "unzip";
    args = ["-q", "-o", archivePath, "-d", destDir];
  } else {
    throw new Error(`unsupported ext: ${ext}`);
  }
  const r = spawnSync(cmd, args, { stdio: "inherit" });
  if (r.status !== 0) {
    throw new Error(`${cmd} ${args.join(" ")} failed with status ${r.status}`);
  }
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const npmRoot = args.npm
    ? resolve(args.npm)
    : resolve(dirname(fileURLToPath(import.meta.url)), "..");
  const distRoot = resolve(args.dist);
  const version = args.version.replace(/^v/, "");

  // SHA256SUMS is generated by the publish job for upload to the GitHub
  // Release but is not re-uploaded as a CI artifact, so it may be absent
  // when prepare.mjs runs against actions/download-artifact output. When
  // present (local dry-runs that fetch from a finalized release), use it
  // as a cross-check; when absent, the sidecar + re-hash path below is
  // still authoritative.
  const sumsPath = join(distRoot, "SHA256SUMS");
  const sums = existsSync(sumsPath) ? loadSha256Sums(sumsPath) : null;

  const vendorRoot = join(npmRoot, "vendor");
  if (existsSync(vendorRoot)) {
    // Start clean so a stale binary from a previous run cannot survive.
    rmSync(vendorRoot, { recursive: true, force: true });
  }
  mkdirSync(vendorRoot, { recursive: true });

  const tmpRoot = join(tmpdir(), `cora-npm-prepare-${process.pid}`);
  rmSync(tmpRoot, { recursive: true, force: true });
  mkdirSync(tmpRoot, { recursive: true });

  const summary = [];

  for (const p of PLATFORMS) {
    const archive = `cr-${version}-${p.triple}.${p.ext}`;
    const archivePath = join(distRoot, archive);
    const sidecarPath = `${archivePath}.sha256`;

    if (!existsSync(archivePath)) {
      throw new Error(`missing artifact: ${archivePath}`);
    }
    if (!existsSync(sidecarPath)) {
      throw new Error(`missing sidecar: ${sidecarPath}`);
    }

    const sidecarHex = readFileSync(sidecarPath, "utf8").trim().split(/\s+/)[0].toLowerCase();
    if (sums) {
      const sumsHex = sums.get(archive);
      if (!sumsHex) {
        throw new Error(`no entry in SHA256SUMS for ${archive}`);
      }
      if (sidecarHex !== sumsHex) {
        throw new Error(
          `sha256 mismatch between sidecar and SHA256SUMS for ${archive}: ${sidecarHex} vs ${sumsHex}`,
        );
      }
    }

    const actualHex = sha256File(archivePath);
    if (actualHex !== sidecarHex) {
      throw new Error(
        `sha256 mismatch between artifact and sidecar for ${archive}: ${actualHex} vs ${sidecarHex}`,
      );
    }

    const extractDir = join(tmpRoot, p.npmKey);
    extractArchive(archivePath, p.ext, extractDir);

    const extractedExe = join(extractDir, p.exe);
    if (!existsSync(extractedExe)) {
      throw new Error(`expected ${p.exe} in ${extractDir} after extraction`);
    }

    const vendorDir = join(vendorRoot, p.npmKey);
    mkdirSync(vendorDir, { recursive: true });
    const targetExe = join(vendorDir, p.exe);
    copyFileSync(extractedExe, targetExe);
    if (p.exe !== "cr.exe") {
      chmodSync(targetExe, 0o755);
    }

    summary.push({
      npmKey: p.npmKey,
      archive,
      sha256: actualHex,
      bytes: readFileSync(targetExe).length,
    });
  }

  rmSync(tmpRoot, { recursive: true, force: true });

  const pkgPath = join(npmRoot, "package.json");
  const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
  pkg.version = version;
  writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);

  // Audit log line per platform. The CI log is where this becomes visible.
  process.stdout.write(`@keton-id/cora ${version} vendor/ prepared:\n`);
  for (const row of summary) {
    process.stdout.write(
      `  ${row.npmKey.padEnd(14)}  ${row.sha256}  ${String(row.bytes).padStart(8)}  ${row.archive}\n`,
    );
  }
}

try {
  main();
} catch (err) {
  process.stderr.write(`prepare.mjs: ${err.message}\n`);
  process.exit(1);
}
